/**
 * \file            modbus_registers.h
 * \brief           Modbus register mapping definitions
 */

/*
 * Copyright (c) 2025 Your Name
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge,
 * publish, distribute, sublicense, and/or sell copies of the Software,
 * and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE
 * AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 * This file is part of Modbus RTU library.
 *
 * Author:          Generated by Modbus Configuration Tool
 */
#ifndef MODBUS_REGISTERS_H
#define MODBUS_REGISTERS_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/**
 * \brief           Enable optimized register mapping mode
 */
#define MODBUS_USE_REGISTER_MAPPING                 (1)

/* Configuration settings */

/* Common settings */
#define MODBUS_SLAVE_ID                          (1)
#define MODBUS_BAUDRATE                          (9600)
#define MODBUS_PARITY                            (0)
#define MODBUS_STOP_BITS                         (1)

/* Device type */
#define MODBUS_DEVICE_TYPE_SLAVE                    (1)

/* Slave-specific settings */
#define MODBUS_RESPONSE_DELAY_MS                 (0)

/* Register counts (optimized memory) */
#define MODBUS_COIL_COUNT                           (0)
#define MODBUS_DISCRETE_INPUT_COUNT                 (0)
#define MODBUS_INPUT_REGISTER_COUNT                 (0)
#define MODBUS_HOLDING_REGISTER_COUNT               (2)

/* Register internal address definitions */

/* Holding Register internal addresses */
#define HR_0000_ADDR                             (0    )  /* Internal addr 0 */
#define HR_0001_ADDR                             (1    )  /* Internal addr 1 */

/* Register mapping indices */
/* Use these indices to access g_modbus_xxx_registers[] arrays */
#define HR_0000_IDX                              (0)
#define HR_0001_IDX                              (1)

/* Direct access macros - use these for easy register access */
/* Example: TEMPERATURE = 34; instead of g_modbus_holding_registers[TEMPERATURE_IDX] = 34; */

/* Holding Register access macros */
#define HR_0000                                  g_modbus_holding_registers[HR_0000_IDX]
#define HR_0001                                  g_modbus_holding_registers[HR_0001_IDX]

/* Register ranges configuration */
#define MODBUS_REGISTER_RANGES_COUNT                (1)

/**
 * \brief           Register range structure
 */
typedef struct {
    uint16_t start_addr;                            /* Starting internal address */
    uint16_t count;                                 /* Number of consecutive registers */
    uint8_t  reg_type;                              /* Register type (0=coil, 1=DI, 3=IR, 4=HR) */
} modbus_register_range_t;

/**
 * \brief           Register mapping structure
 */
typedef struct {
    uint16_t internal_addr;                         /* Internal address (for Modbus protocol) */
    uint16_t array_index;                           /* Index in data array */
} modbus_register_map_t;

/* External variable declarations */
extern const modbus_register_range_t g_modbus_register_ranges[];
extern const modbus_register_map_t g_modbus_holding_register_map[];
extern const modbus_register_map_t g_modbus_input_register_map[];
extern const modbus_register_map_t g_modbus_coil_map[];
extern const modbus_register_map_t g_modbus_discrete_input_map[];

extern uint16_t g_modbus_holding_registers[];
extern uint16_t g_modbus_input_registers[];
extern uint8_t  g_modbus_coils[];
extern uint8_t  g_modbus_discrete_inputs[];

/* Function prototypes */
uint8_t     modbus_is_register_valid(uint16_t addr, uint8_t reg_type);
int32_t     modbus_get_register_ranges(const modbus_register_range_t** ranges);
void        modbus_registers_init(void);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* MODBUS_REGISTERS_H */
